### ISSUE TITLE
Use /environments/{environment_api_key}/edge-identities/{edge_identity_identity_uuid}/edge-featurestates/ for feature override 

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#1048]
Instead of `/api/v1/environments/HALuMcoNiqFCVwYtJdddyv/edge-identities/{edge_identity)uuid}/featurestates/`

when overriding from 
![image](https://user-images.githubusercontent.com/18366226/166652729-1af7bf17-cf9c-4c04-a42d-caf1866dcf29.png)

**Comment by kyle-ssg** [comment]
I've done this however I think we've deemed that we can't actually show this tab for edge because https://api-staging.flagsmith.com/api/v1/environments/R8Pkw76haSiBZz7yQiECwc/featurestates/?anyIdentity=1&feature=3614&page=1 isn't possible @gagantrivedi , though maybe reopen if you reckon this isn't the case

**Comment by gagantrivedi** [comment]
Yeah, that's true, but I think we are planning to deprecate `anyIdentity` anyway, right @matthewelwell?

**Comment by gagantrivedi** [comment]
However, I can make `/environments/{environment_api_key}/edge-identities/{edge_identity_identity_uuid}/edge-featurestates/` support query param `feature` that I think front-end can use to filter?

**Comment by gagantrivedi** [comment]
Added here: https://github.com/Flagsmith/flagsmith/pull/1056

**Comment by matthewelwell** [comment]
Yeah, the problem here @gagantrivedi is that the `anyIdentity` parameter basically shows _all_ user overrides for all identities (not just a single identity) in a given environment. We just can't achieve that with the data structures in dynamo (without massive pain) so we'll just have to hide the tab for the edge identity viewset.

**Comment by gagantrivedi** [comment]
Ah yeah, that makes sense
