### ISSUE TITLE
A scheduled flag change causes the value to go from null > ""

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1107]
- Create flag, don't specify a value
- Push the flag thru a scheduled change request, only changing the boolean value of the flag
- Wait for the scheduled time to pass
- Flag value goes from `null` to `""`

**Comment by gagantrivedi** [comment]
Ah, it's because front-end is sending "" when creating change request
![image](https://user-images.githubusercontent.com/18366226/168273732-07775955-1660-467c-98b2-d26341c31c04.png)

Event tho backend send null
![image](https://user-images.githubusercontent.com/18366226/168274020-9d270e01-d3c3-466d-82b2-de5613a3981f.png)

**Comment by gagantrivedi** [comment]
@kyle-ssg  Let me know if you need anything else

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/commit/352414a0021effce67c9cb39f8250f035ac93196
