### ISSUE TITLE
Audit log filters not working correctly

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1137]
1. Going from a filtered env to all envs doesnt clear the env ID from the API call
2. Filtered env list isnt showing all records

**Comment by kyle-ssg** [comment]
I realised in the end that I was filtering the results on the frontend due to the environment param appearing not to work, given the following 2 endpoints:

audit/?project=112&environment=270&page_size=20
audit/?page_size=20&project=112

They appear to return the exact same results, also it returns 1500 results.

**Comment by kyle-ssg** [comment]
Related https://github.com/Flagsmith/flagsmith/issues/738

**Comment by matthewelwell** [comment]
Reopening for frontend work to get paging working.
