### ISSUE TITLE
Allow for reordering of Environments

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1264]
It would be nice to be able to reorder environments. We would need to store their order in the database, so requires API, endpoints and Front End.

**Comment by kyle-ssg** [comment]
I could be wrong but I think this can be closed? The UX no longer calls for an order really with it being a select.

**Comment by dabeeeenster** [comment]
Yep

**Comment by dreysolano** [comment]
@dabeeeenster @kyle-ssg As a customer, I would still like to be able to sort my environments. Just because it's a select menu doesn't mean control over order wouldn't be desirable, rather than having them ordered by created date. For example, currently I have:

Dev
Prod
Test
Stage

And would be nice for them to be ordered like so:

Dev
Test
Stage
Prod
