### ISSUE TITLE
Flag Analytics graph should show zero traffic data points

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1266]
It seems that the graph does not show time points with a zero count - it should, and the graph should always show the full time period selected.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/173290/177032632-33d8d3ea-f739-41df-832b-77fa757fc880.png">

**Comment by kyle-ssg** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/8608314/177321516-0f5a6489-f8ac-40da-aa6b-cfd7ed184dfa.png">

**Comment by kyle-ssg** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/8608314/177322015-268a3a50-d8c9-43d7-a269-8aeafb420da4.png">

This is done, however, I can see an API issue whereby the last date is returned twice with 2 different values

Message me if you can't replicate

**Comment by matthewelwell** [comment]
@kyle-ssg Is it always just the last date?

**Comment by kyle-ssg** [comment]
It looks like an API change has been made to make the period work which meant that the FE was showing just 1 day (Since it doesn't break down by hour this option no longer makes sense), I've adjusted the frontend so that it requests 28 days as before however it looks like there's now a max of 12 days.

**Comment by kyle-ssg** [comment]
Hmm can't replicate this in prod - will close
