### ISSUE TITLE
Calculate SaaS Seat, Project and API limits from Chargebee JSON

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1296]
For an `Organisation` we should compute the following data:

- `max_seats`
- `max_projects`
- `max_api_calls`

and provide it to the Front End in the Organisation object. 

This data will be calculated based on JSON metadata present in the following chargebee objects:

- Subscription Plan
- Add Ons

To calculate the correct figures, iterate through all Subscriptions and their plans and add ons, and sum the values based on JSON metadata. E.g. a plan could have the following meta data:

```json
{
  "seats": 5, 
  "api_calls": 1000000
}
```

If there is no data for e.g. `projects` then do not limit that amount in the front end. 

Default values in the event of their being no subscription for the organisation in Chargebee (e.g. if they just signed up) for this should be taken from a feature flag config value. 

## Sample Data

Plan: https://flagsmith-test.chargebee.com/plans/1813558/details
add on: https://flagsmith-test.chargebee.com/addons/548239/details

**Comment by gagantrivedi** [comment]
We have added a new endpoint 
![pingg](https://user-images.githubusercontent.com/18366226/179986686-8f591cea-e604-4e98-a265-f2d72826223d.png)

**Comment by dabeeeenster** [comment]
@gagantrivedi is this now driving the data for the sales dashboard? I think for the organisation details page we should do that. Doing it for the list page might be too many api calls?

**Comment by gagantrivedi** [comment]
> is this now driving the data for the sales dashboard?

No, we did not change anything on the sales dashboard

**Comment by dabeeeenster** [comment]
> > is this now driving the data for the sales dashboard?
> 
> No, we did not change anything on the sales dashboard

Can we add that to the PR?

**Comment by matthewelwell** [comment]
It was merged: #1310. We can add a _new_ PR if needed.

**Comment by dabeeeenster** [comment]
Yep new PR please!

**Comment by kyle-ssg** [comment]
@gagantrivedi, this endpoint throws a 500 for me. Try with the following on prod:

```
/organisations/13/get-subscription-metadata/
```

**Comment by matthewelwell** [comment]
This is because organisation that organisation has been 'hacked' to mimic a chargebee subscription but it doesn't actually have one. I can write some code to handle it but it will just throw a 4xx in this case instead I guess, or maybe it should return some sane defaults? 

@dabeeeenster is it possible to set up an organisation which has a valid chargebee subscription that @kyle-ssg can test with?

**Comment by dabeeeenster** [comment]
ok have communicated a test sub with @kyle-ssg on staging

**Comment by matthewelwell** [comment]
@kyle-ssg @dabeeeenster at the moment, the new endpoint returns 404 if the organisation has no subscription. I've created a PR (#1365) which, in the case that the organisation has a subscription but it's _not_ a valid Chargebee subscription, returns the defaults for the free plan or uses the data from the subscription object (for example for a Xero subscription). I'm thinking we should do that if the organisation has no subscription at all too? Then the FE doesn't have to care about the defaults, etc.

**Comment by kyle-ssg** [comment]
Just read this. At the moment it will for max_seats since that's the only thing we use but the above sounds like a good idea.

I see that we're also including max_projects, I don't think I'd ever be able to use this since I assume this endpoint is restricted to org admins? So unless we opened up the endpoint I think the validation of this should happen at the create project endpoint.
