### ISSUE TITLE
Front end should never call Edge API directly - it should always go through core

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1330]
Calling edge directly can cause race conditions with DynamoDB replication.

Currently this is affecting Identity Flag overrides.

**Comment by kyle-ssg** [comment]
This now uses the core SDK endpoint instead of the edge. If we want it to use an admin endpoint I'd need an endpoint that returns a user's flags whilst evaluating their segment overrides.

**Comment by dabeeeenster** [comment]
Does this need something backend?

**Comment by matthewelwell** [comment]
I just want to flesh this issue out a little bit. 

As I understand it, we're trying to remove the call to, e.g. https://edge.api.flagsmith.com/api/v1/identities/?identifier=<identifier> when a user browses to the detail page for a given identity. At the moment, changes to an identity made via the dashboard are written to DynamoDB in London and there is then a delay in replicating that data to the rest of our edge locations. This means that, for users browsing the dashboard in e.g. California, when they make a change to a flag for a given identity they see the change occur but then it does not seem to persist (as the frontend is doing a PUT, then a GET). 

What we need to know is exactly how the frontend is using the endpoint above to see how we can provide the same data via core API endpoints. Can we achieve this with existing endpoints or do we need to replicate the /api/v1/identities endpoint in the Core API but with the data from DynamoDB 🤔? 

Other considerations: 

 1. Can we bypass the global accelerator by providing a header / query parameter perhaps? That way we could just force the request from the dashboard to route to London and we wouldn't see this issue. 
 2. Should we write overrides and traits to Postgres and the frontend can call the core API identities endpoint instead (this is likely not a valid solution, not least because of the migration we'd be forced into to backfill data that doesn't currently exist)

**Comment by matthewelwell** [comment]
Discussed this with @kyle-ssg. I am going to have a look at what's involved in creating a new endpoint which will give the frontend all of the information that it needs to generate the features panel on the identities page. Currently the frontend is doing a lot of work to determine which feature states are overridden for the identity, which are coming from a matching segment and which are just the environment default. 

It should be possible for us to create an endpoint which returns all of this information in a single request and retrieves the relevant information from either dynamo or postgres depending on the context.

**Comment by dabeeeenster** [comment]
Think idea 1 is sort of interesting/clever but feel like its better to just go to the source of truth data in the core API whenever required. If this means going to Dynamo I think that should be the first/ideal solution. 

But also think that where there are opportunities to simplify/refactor the interface between FE and BE we should take it.

**Comment by matthewelwell** [comment]
@kyle-ssg I've deployed a new endpoint to staging which should give you all the information you need in a single request, it will even tell you the name of the segment that it's being overridden for (although the API docs aren't quite correct for this - I'll update those). Segment will actually give you an object of the form `{"id": <numeric id>, "name": "<segment name>"}`. 

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/14089968/181786323-b8bbf8f7-63ee-4cd0-8aaf-dd2ed563fd18.png">

In writing this, I've also realised that this logic doesn't currently take into account segment priorities so I will fix that up next week but the structure of the endpoint itself will not change so you should be able to integrate with it regardless.

**Comment by matthewelwell** [comment]
Fixes for the above comment are [here](https://github.com/Flagsmith/flagsmith/pull/1346).

**Comment by matthewelwell** [comment]
@kyle-ssg I've added an endpoint for core identities now that returns exactly the same data structure (currently only in staging). 

```
GET /api/v1/environments/:key/identities/:id/featurestates/all/
```

**Comment by kyle-ssg** [comment]
Live under use_admin_identity_featurestates - @matthewelwell  this all looks good on core but edge is throwing a 500. Messaged curl in slack

**Comment by matthewelwell** [comment]
Released fix for above and enabled flag in production.
