### ISSUE TITLE
Allow configuration of UI variations per environment

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1475]
It would be nice if users could configure some level of UI prompt when viewing the dashboard in the context of a specific environment. The primary use case would be to perhaps show a warning or alter the colour scheme if viewing the dashboard in the context of a production environment.

**Comment by dabeeeenster** [comment]
They can use the butter bar to do this to a degree, but maybe adding a UI base element colour would be useful too?

**Comment by sw-tracker** [comment]
We would love this feature. Due to regulations we are not allowed to use the same deployment of flagsmith on different environments, so we currently have flagsmith deployed 5 times.

All other software in our company follows a colour coding so that if you login to acceptance, you know where you are. And more importantly, you know when you are in production and don't accidentally do something thinking you were in another environment.

We are currently using the `butter_bar` flag to set the name of the environment where the user is. However, this does not work for production DB clones (where our support level employees click around when a customer calls with an issue). We were thinking that you could make `butter_bar` an environment variable so we can configure it on our OpenShift templates.

**Comment by dabeeeenster** [comment]
@kyle-ssg @matthewelwell suggest we add an item to `/config/project-overrides` for a butter bar override that can be defined as an ENV var, and then on the Front End have this take precedent over a flag value if the env var is configured. Thoughts

**Comment by dabeeeenster** [comment]
Superceded by #1720
