### ISSUE TITLE
Sales Dashboard times out on main results page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1587]
We are now grabbing data from both Influx and Chargebee, which is too slow. We need to either:

1. Remove the CB and Influx data from the main results page and only show it on the Org detail page
2. Store some of that data locally and update it regularly as part of a cron job

Its powerful and helpful being able to sort the accounts by usage, and seeing immediately who is over their API plan or seats. So my preference would be for 2. The fact that the data is maybe 24h stale is not an issue. Live data can be pulled into the org detail page.

**Comment by matthewelwell** [comment]
Having done some investigations here, this has been caused (or at least pushed over the edge) by the fact that we're now making a request to CB for each row in the table. I was under the impression that this information was cached, however, the issue is that we need to retrieve the subscription from CB to determine their plan and addons so we can then lookup in the cache what their available seats and API calls are. 

This can be seen here: https://github.com/Flagsmith/flagsmith/blob/main/api/organisations/chargebee/chargebee.py#L110

The issue is that this was slow even before we added the chargebee information so we should try to tackle both the Influx data and the CB data in one swoop. 

One option would be to have a separate DjangoModel which holds this information in a 'cache' for a given organisation. We could create an ECS task that runs on a schedule to update this, however, if we did this once per day for every organisation, we may incur costs from CB API limits and we would also need to consider the ECS task resources as it would likely take some time to loop through all the organisations. 

I'd like to think a little bit more about how we can achieve this, however, at a first glance it's going to be quite tricky to achieve option (2) in an elegant fashion.

**Comment by dabeeeenster** [comment]
CB have a reasonably decent api limit which would work if we throttled the loop. We could maybe limit the data ingest to organisations that have had a login within 24 hours or something like that? 

Long term we can listen to CB webhooks and update our local CB state when theirs changes.
