### ISSUE TITLE
Add "Manage segment overrides" environment permission

### ISSUE THREAD

**Issue by luk355** [SolidStateGroup/bullet-train-api#1676]
Segment overrides allows release of a specific feature to broader set of users. Not all Flagsmith users should have access to update this settings, therefore, I would be great to have dedicated "Manage segment overrides" environment role which would limit this.

This feature would also work well with the 4 eyes as segment overrides are not hidden behind the feature flag.

## Acceptance Criteria

 - [ ] Users and groups can be given a new 'Manage Segment Overrides' permission
 - [ ] Non-Admin users with the 'Manage Segment Overrides' permission in a given environment are able to add, edit and remove segment overrides for flags in that environment
 - [ ] Non-Admin users without the 'Manage Segment Overrides' in a given environment are able to view segment overrides for flags in that environment
 - [ ] Non-Admin users without the 'Manage Segment Overrides' in a given environment are not able to add, edit or remove segment overrides for flags in that environment

**Comment by dabeeeenster** [comment]
This sounds sensible to me - thoughts @gagantrivedi @kyle-ssg @matthewelwell ?

**Comment by matthewelwell** [comment]
Yes, for sure.

**Comment by zachaysan** [comment]
The backend work for this feature is nearly complete. During testing I determined that we are going to need some frontend rule changes to make the interface work as expected for our customers.



![Image](https://github.com/Flagsmith/flagsmith/assets/222715/e7a015bb-996d-4e44-aa1a-053d9c695c3a)

Right now the segment overrides section of the interface is still active looking if a user has the ability to edit features. Since this is a different permission, however, we'll now need to check if the user has the `MANAGE_SEGMENT_OVERRIDES` permission and only show a read-only version of the interface if they do not have it.

In addition to the above, please also hide the Create Feature-Specific Segment button if the user is missing the project permission `MANAGE_SEGMENTS` since they will not be able to create a segment if that permission is missing.


![Image](https://github.com/Flagsmith/flagsmith/assets/222715/5bd19728-e0e7-4c90-a7cc-943a8a8a0467)
