### ISSUE TITLE
Have read-only permission for 'users'

### ISSUE THREAD

**Issue by bao-ujet** [SolidStateGroup/bullet-train-api#1773]
We have groups that will give 'View Project' access to our members. However, that only gives access to the features, not the 'users' section. We would like to have View Project include viewing the users, or have a different config that'll control read/write access to users.

gz#219

**Comment by dabeeeenster** [comment]
Having this as a new, seperate permission seems like a good idea.

**Comment by siraj-mx51** [comment]
👍 very important to us

**Comment by matthewelwell** [comment]
Hi @bao-ujet, I just want to clarify some things here since some of the terminology used in your issue report doesn't quite align with the entities in the platform. 

When you say 'View Project' - do you actually mean 'View Environment'? Since, without at least one View Environment permission, the View Project permission does not provide access to any features OR users (as they are viewed at the environment level in all cases). 

Therefore, what I'm suggesting is a new permission at the Environment level which gives read only access to the 'Users' page in that environment. Does that work for your use case?

**Comment by bao-ujet** [comment]
Hi @matthewelwell. Yes, thanks for the clarification. That's exactly what we want, at the environment level. I do see 'Manage Identities' so we just need a 'View Identities' or similar.
