### ISSUE TITLE
traits don't like large numbers

### ISSUE THREAD

**Issue by TD-4242** [SolidStateGroup/bullet-train-api#1789]
I was trying to set a trait to the value of `Date.now()` but was getting 500 errors:

Here you can see I set the trait `testDate` and get a 500 error but if I reduce the size by `/ 1000` it doesn't produce the error and the trait gets set.

![image](https://user-images.githubusercontent.com/3487671/208494644-f9b74042-dd6a-442e-961c-2e457f9149e9.png)

gz#226

**Comment by matthewelwell** [comment]
This is a bit of a legacy issue but one that is very difficult to solve technically on our side without a major impact on the API. The reason this is happening is because integer value traits are currently stored as 32 bit integers. We could increase this to 64 bit, however, we'd just be kicking the can a little further down the road so I am reluctant to do this. 

The proper solution is to always store the value as a string and get the clients to send the correct value type and do the conversion as required, however, this is a major overhaul of the API (see #1667).

For the time being, as a workaround, users should either send the data as a Float or a string and handle the conversion themselves. 

I am going to resolve this issue as the full solution is already covered here #1667.
