### ISSUE TITLE
Pipedrive QOL tweaks

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1952]
There are two requirements which would streamline things:

- Have an internal blacklist of email domains that _do not_ trigger pipedrive entity creation. 
- Don't create pipedrive entities if the new account is part of a paid organisation.

## Current Email Blacklist

- gmail.com
- googlemail.com
- outlook.com
- hotmail.com
- icloud.com
- me.com
- aol.com
- @yahoo.* (they have subdomains)

**Comment by MikeBoerma** [comment]
Can we also attach First Name, Last Name, Company associated with lead?

**Comment by matthewelwell** [comment]
@MikeBoerma the company is already taken from their domain and an organisation is created in Pipedrive based on this. Are you looking for something else here? 

Regarding the First Name / Last Name, since we're using 'Lead' here, there aren't currently fields in Pipedrive for these. 

I guess perhaps the integration should create a lead based on the organisation (if it doesn't already exist) and then create a person for the new sign up to attach to the lead?

It's a bit of a confusing data model tbh, I guess 'Leads' should map 1-1 with 'Deals', which an organisation might have multiple of, whereas realistically organisations signing up to our SaaS platform will likely only have one 'Lead' / 'Deal'. 

Probably best to chat this through in a bit more detail?
