### ISSUE TITLE
Bulk Identities not update all traits in FM

### ISSUE THREAD

**Issue by darioboverio** [SolidStateGroup/bullet-train-api#2002]
**Describe the bug**

The problem is happening randomly. The traits are not fully updated on FM, maybe it only applies some of them but there are others which are missing.
It's hard to test this because we’ve made a lot of tests locally and it worked fine, but then, when we use the App in our staging/production environment, with so many events coming, the issue appears. This is important because we are creating segments for specific features, where some users should be included, and because of the missing trait they are not targeted. I’ve some evidence to send you, where we are sending a payload with many traits and not all of them are impacted on FM.
Our flow consist in updating user information all the time, when the user uses the App. So every time an update is made, we call bulk identities endpoint to apply the user information as traits on FM. In the following iterations, we might call the endpoint with the same traits as before and new changes, which can include:

1. A trait value was updated
2. A new trait is added

We've done so many different test locally, like:

1. Making different requests, step by step, and it worked fine
2. Looping requests and it also worked fine
3. Send request in different order as expected from the App (just to make sure that is not the problem) and it worked fine

But then, on staging/production, where we are getting so many events, we found cases working properly but a lot of cases with missing traits. I sent 2 cases on Rain Slack channel (#external-flagsmith).

**Expected behavior**
All traits from every request must be available on user profile in FM.

**Screenshots**
Included in the evidences sent on Slack (#external-flagsmith).

**How are you running Flagsmith?**
- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional information**

Endpoint: PUT https://edge.api.flagsmith.com/api/v1/bulk-identities 
Payload: On evidences on Slack (#external-flagsmith).

gz#503

**Comment by matthewelwell** [comment]
A quick update on this issue: @darioboverio and I have been working together to try to reproduce / diagnose the issue but so far have been unsuccessful. One thing that we've noticed is that sending multiple identities in a single request causes the request to fail silently. I have raised an issue for this in our separate private repo [here](https://github.com/Flagsmith/edge-api/issues/140). It is evident from testing, however, that this is not the cause of the issue raised here. 

Additionally, further testing has been carried out to try to reproduce the issue with no success. I have written a (fairly crude) python script [here](https://gist.github.com/matthewelwell/425404d04efa63221e066da987f24386) which allows the user to exercise the bulk-identities endpoint programmatically by sending random numbers of identities with random amounts of traits to the endpoint repeatedly and verifies that the traits have been applied successfully. In over 1 hour of continuous testing, this was unable to reproduce the issue. 

We have also investigated the case that there are overwrites happening due to calls made to other endpoints. This could occur due to writing identities to the Core API (which will then cause an overwrite in Edge) and also making a request to eg. `/identities` in Edge with trait values set as null. This investigation has, again, proved unsuccessful. 

The next steps here are that @darioboverio will reimplement the logic to use the `/identities` endpoint which should help us verify if the issue is with the bulk identities endpoint itself or elsewhere.

**Comment by matthewelwell** [comment]
Further update: 

>The next steps here are that @darioboverio will reimplement the logic to use the /identities endpoint which should help us verify if the issue is with the bulk identities endpoint itself or elsewhere.

Following the reimplementation of the logic, the issue no longer presents itself. Further investigation is required to try to reproduce issues on the bulk-identities endpoint.

**Comment by arpanpreneur** [comment]
We are using Self Hosted Flagsmith and we have faced the following problem, which looks to me is this exact issue.

We have company_id and user_id as a trait on users. When we turn on features for everyone in the company, we typically just make a Segment Override with company_id = something. This has been working for us for years without problem. Only recently we have started seeing, when we create new users for newer companies, the company level config is not for some users automatically being applied as it doesn't have the trait.

**Comment by matthewelwell** [comment]
Hi @ArpanKIIT2017, thanks for getting in touch. From reading your comment, I'm not sure that your issue can be related since the bulk identities endpoint is only available in our Edge API which is not available as part of our self hosted offering. If you are able to provide more details on your issue in a separate GH issue then we'd be happy to take a look into it when we have time. Please do open a new issue, however, since it is unrelated to this thread. Please also provide as much information as possible (include code snippets where applicable).

**Comment by arpanpreneur** [comment]
Thanks @matthewelwell for your response.

**Comment by matthewelwell** [comment]
Closing this issue due to an inability to reproduce, and inactivity on the issue itself.
