### ISSUE TITLE
Timezone improvements for Scheduled Flags

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2098]
Currently the frontend shows the following for scheduled flags

![image](https://user-images.githubusercontent.com/8608314/230314001-edce0468-2485-420e-a17b-5c01383578fc.png)

We want to give more certainty around times than is currently being done. We should

- Instead of Europe / London we should show the timezone e.g. UTC +1
- We should show a note if the scheduled timezone is different to the current timezone (If possible) e.g. Note, your local timezone will be different to now on the above date), it will be scheduled for x date and time UTC

**Comment by alceil** [comment]
Can I work on this ?@dabeeeenster

**Comment by dabeeeenster** [comment]
> Can I work on this ?@dabeeeenster 

Sure!

**Comment by alceil** [comment]
Thanks @dabeeeenster

**Comment by alceil** [comment]
![image](https://user-images.githubusercontent.com/47685349/231697869-0f68b387-962d-4c8d-a5c1-ef70e94736fa.png)
New change is something like this is this okay? @dabeeeenster

**Comment by matthewelwell** [comment]
That looks good @alceil. One thing that would be good to clarify here is what happens in the case that you're scheduling a change for the future that spans a change in timezone. For example, if I schedule a change now in the UK, it will show UTC+1 because we're in BST. BUT, if I schedule the change for November, let's say, the timezone in the UK will actually be GMT (which is the same as UTC). 

Let's take an example to try and think this through: 

I'm in the UK, my current timezone is BST (UTC+1). I schedule a change for November 22nd at 11am. The logic here (I think) will send the API a value of something like `"2023-11-22T10:00:00.000000+00:00"` as it sends the UTC value (again, I think). This will mean that the change will _actually_ happen at 10am in the UK on the 22nd November, because the timezone in the UK is, at that point, the same as UTC. 

Am I correct in my assumptions here? Is there a solution to this?

**Comment by jainpawan21** [comment]
> That looks good @alceil. One thing that would be good to clarify here is what happens in the case that you're scheduling a change for the future that spans a change in timezone. For example, if I schedule a change now in the UK, it will show UTC+1 because we're in BST. BUT, if I schedule the change for November, let's say, the timezone in the UK will actually be GMT (which is the same as UTC).
> 
> Let's take an example to try and think this through:
> 
> I'm in the UK, my current timezone is BST (UTC+1). I schedule a change for November 22nd at 11am. The logic here (I think) will send the API a value of something like `"2023-11-22T10:00:00.000000+00:00"` as it sends the UTC value (again, I think). This will mean that the change will _actually_ happen at 10am in the UK on the 22nd November, because the timezone in the UK is, at that point, the same as UTC.
> 
> Am I correct in my assumptions here? Is there a solution to this?

Hi @matthewelwell 
I think this can be handled via a `Day Light Saving` check.
There will be a small fix.
Can you please assign this to me?

**Comment by matthewelwell** [comment]
@kyle-ssg I think [this PR](https://github.com/Flagsmith/flagsmith/pull/3565) included sufficient work to close this issue, do you agree?
