### ISSUE TITLE
Unable to retrieve the project UUID

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2103]
The Project UUID is important for the Terraform provider, however, it is not currently possible to retrieve this from the UI.

**Comment by strugee** [comment]
To clarify (I reported this via support): there doesn't seem to be a JSON view for projects, even though I have JSON views turned on in settings and can see them for most other kinds of objects. Or if there is, it's virtually impossible to find.

I _believe_ this is also a recent regression because a few weeks ago when I was testing our integration library, I was able to retrieve this UUID no problem.

**Comment by strugee** [comment]
For folks stumbling on this issue, the workaround is to go to the project page, open devtools, refresh to refetch everything from the network, and filter for `/api/v1/project`. There you can see the JSON project object in the server response where you can retrieve the UUID.

If the response is blank, you probably selected the `OPTIONS` request instead of the `GET` request.

**Comment by gagantrivedi** [comment]
Yeah, we don't have JSON data view for Project, right? @kyle-ssg

**Comment by kyle-ssg** [comment]
Yes, JSON references were created for this reason. You can enable it in account settings.

<img width="819" alt="image" src="https://user-images.githubusercontent.com/8608314/231105069-0a7640e7-adc5-4e82-9b80-216d95eee4fc.png">

From this, all pages will have context based raw JSON.

I can see however, the project list and project settings do not have a reference. I'll just get a PR up to include that.


Edit: With the attached PR, this will be accessible  via project settings.
