### ISSUE TITLE
https://app.flagsmith.com/demo is broken

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2201]
Go to https://app.flagsmith.com/demo and just get:

> Oops
> We could not login to the demo account please contact Support

**Comment by bharathkalyans** [comment]
I hope this issue is not closed!
- Found a bug where when visiting `https://app.flagsmith.com/{randonSlug}` the page is showing blank.
- Take a look below 👇🏻
<img width="1440" alt="Screenshot 2023-05-16 at 10 49 18 AM" src="https://github.com/Flagsmith/flagsmith/assets/49526472/edf38e53-1b1b-4070-8b1c-fcedc25f9ef1">

- Rather it should be showing the 404 error page/component, like 👇🏻

<img width="1440" alt="Screenshot 2023-05-16 at 10 49 39 AM" src="https://github.com/Flagsmith/flagsmith/assets/49526472/268d6485-4985-4df5-8979-8ef07da4bd52">

**Comment by bharathkalyans** [comment]
I believe this `<Route component={NotFoundPage} />` should be `<Route path="*" component={NotFoundPage} />` 
file 👉🏻 : [frontend/web/routes.js](https://github.com/Flagsmith/flagsmith/blame/main/frontend/web/routes.js) {line 166}

**Comment by bharathkalyans** [comment]
@dabeeeenster I can do a PR 😀, it's a one line fix right 😅?

**Comment by matthewelwell** [comment]
Hey @bharathkalyans , sure - we'd love to get a PR here!
