### ISSUE TITLE
Ensure that the data about max API calls and actual API calls is on-sync and up to date

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#2268]
**Is your feature request related to a problem? Please describe.**

There are discrepancies in the max API calls number between the sales dashboard and the Django admin views for some subscriptions. Also, we need to ensure that the number of API calls is kept up to date for every organisation.

1. Go to the sales dashboard and pick an organisation with a start-up plan. See that the max number of API calls is 1M.
2. Go to the Django admin page and search for the same organisation. See that the max number of API calls is 50K.

**Describe the solution you'd like**
The organisation subscription information must be kept on-sync. The same number of max API calls should be shown in the sales dashboard and the Django admin pages.

**Comment by khvn26** [comment]
https://github.com/Flagsmith/flagsmith/issues/2246 Related? @matthewelwell

**Comment by matthewelwell** [comment]
> #2246 Related? @matthewelwell

No, I don't think so. I think the issue here is that there are 2 places that this data is located. One is in Chargebee (which is the correct data), the other is in the DB for the API itself. This provides default values for those organisations that don't have data in Chargebee. 

The data from Chargebee can be retrieved from the `organisations/:id/get-subscription-metadata` endpoint.

To resolve this issue, we should either: 

 1. Remove the data from the organisation on retrieval
 2. Retrieve the data from CB when we retrieve the organisation (since this data is cached, maybe that's ok)
