### ISSUE TITLE
Projects can be created via API under the free plan

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#2835]
**Describe the bug**

As an admin user of a free plan org, a call like this:

```
curl 'https://api.flagsmith.com/api/v1/projects/' \
  -H 'authority: api.flagsmith.com' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Token <user token>' \
  -H 'content-type: application/json; charset=utf-8' \
  -H 'dnt: 1' \
  -H 'origin: https://app.flagsmith.com' \
  -H 'referer: https://app.flagsmith.com/' \
  -H 'sec-ch-ua: "Chromium";v="117", "Not;A=Brand";v="8"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' \
  --data-raw '{"name":"hacked","organisation":<org id>}'
```

will result in a new project created, even though the plan forbids it. 

**Expected behavior**

A 403 error returned and no project created.

**Screenshots**

<img width="1212" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/979078/c9f7addc-a312-45a5-b818-529b18f574dd">

(Two 'hacked' projects created via API)

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Comment by tushar5526** [comment]
Hey, is this issue still up for grabs?

**Comment by matthewelwell** [comment]
@tushar5526 yes, this is still up for grabs, although it is functionality related to our paid plans rather than anything that particular benefits the open source community. If you still feel like you want to take it on, please let me know and I can assign it to you. For reference, we do have some logic for determining paid plans in the code that already exists, e.g. for setting the `minimum_change_request_approvals` value on an environment.

**Comment by tushar5526** [comment]
I would like to go ahead with it. Thanks for the reference.

**Comment by tushar5526** [comment]
Hey @matthewelwell, is there any logic already in place at the backend that restricts user features according to their plans? 

I was able to enable the Frontend to create multiple projects by setting the return value to `True` for this function on my local - https://github.com/Flagsmith/flagsmith/blob/main/frontend/common/utils/utils.tsx#L271

It seems that the logic to check which plans are enabled is present in the front end rather than the back end. Can you help me with some more context on what needs to be done in this issue?

**Comment by matthewelwell** [comment]
At the moment, the only logic we have in the back end is contained here: [organisations/subscriptions/serializers/mixins.py](https://github.com/Flagsmith/flagsmith/blob/main/api/organisations/subscriptions/serializers/mixins.py). I guess the ideal solution would be to generalise this logic and reuse it in this serializer mixin as well as the logic we add for preventing creation of projects. 

I guess the ideal place for it to exist on project creation would still be in the serializer validation so it certainly all seems fairly closely related.
