### ISSUE TITLE
Avoid excess calls to `get-subscription-metadata`

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#2950]
We observed a rapid increase to call count for `/api/v1/organisations/{pk}/get-subscription-metadata/`:

<img width="786" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/979078/36ebaf36-0408-4b4a-9b1a-4661bb352ab2">

Majority of those result in 404s and 403s:

<img width="465" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/979078/836876c4-1b9d-40ed-bbfd-00d07b09cc91">

We need to think of a way to rework the logic to minimize those calls.

**Comment by novakzaballa** [comment]
@matthewelwell I would propose returning a non-error response from the BE when the user organization hasn't a subscription, we could instead return a 200 response with a body like {"subscription": null} in that case and otherwise can return:
```
{
  "subscription": {
    "max_seats": 0,
    "max_api_calls": 0,
    "max_projects": 0,
    "payment_source": null,
    "chargebee_email": "user@example.com"
  }
}
```

**Comment by matthewelwell** [comment]
Looking at the code in `OrganisationViewSet.get_subscription_metadata` I'm not too sure why we're doing the `organisation.has_subscription()` check since all organisations should have a subscription (I've just checked production data and there are a few exceptions to this, all created on the 27th February this year) and `Subscription.get_subscription_metadata()` will handle the free plan data. 

My suggestion would be to just remove that check and we'll fix the data for those organisations (possibly as part of a migration in the PR to fix this issue too).

**Comment by novakzaballa** [comment]
I haven't worked directly on that part of the BE code, but in my experience, the endpoint is returning 404 for all free subscription orgs, and that's the case for my own free subscription org, created after I joined the company in April:
![image](https://github.com/Flagsmith/flagsmith/assets/41410593/6b8b8a50-28dd-421c-9d5d-2292d9c34293)

**Comment by matthewelwell** [comment]
Sorry, yep, I was adding that comment for context as @zachaysan is going to start working on it.
