### ISSUE TITLE
Chargebee upgrades can cause a second subscription to be created

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#312]
We need to implement subscription upgrades via the API. 

## To Do

- [ ] Create a new API endpoint that allows organisation administrators to upgrade to Scale Up accounts - effectively to change the Chargebee `plan-id` to `scale-up-v2`. The API needs to update the plan within the Subscription object, and also set the number of seats in the Subscription to 5.
- [ ] Modify the front end to hit this API when clicking on the upgrade button. This should send the chargebee `plan-id` to the API above.
- [ ] Create a "Youve upgraded" modal with the new information.

**Comment by gagantrivedi** [comment]
The backend already supports this. front-end just needs to add update subscription(currently it's new subscription) modal on the front-end.

**Comment by kyle-ssg** [comment]
Unsure of what's required here, the frontend currently calls api/v1/organisations/:id/update-subscription/ when chargebee calls back. Assign back to me when this is fleshed out a bit better.

**Comment by dabeeeenster** [comment]
OK i think this is just fundamentally not following the same steps described [here](https://www.chargebee.com/checkout-portal-docs/checkout-existing-tutorial.html). We need an endpoint similar in that page to `generate_checkout_existing_url` which AFAICT we don't have, and the FE is not attempting to call when upgrading the sub.

**Comment by matthewelwell** [comment]
[This PR](https://github.com/Flagsmith/flagsmith/pull/472) ads a new endpoint to get the URL to the hosted page for an existing subscription, the FE should call this and direct the user there to upgrade instead of generating a new hosted page and then call the 'update-subscription' endpoint with the id of the hosted page as normal. 

The issue we have at the moment (as I understand it) is that the FE is generating a brand new hosted page unassociated with an existing subscription id and hence a new subscription is being created rather than the existing one being amended. 

Note that this flow is only applicable for organisations with existing subscriptions of course. Any new organisations / orgs without a subscription id will need to follow the current workflow.

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/143089475-feede57f-8b9f-4695-8a9f-6c5ee93e2d8f.png)

Frontend will be live under the flag "upgrade_subscription", it looks like the hosted URL that comes from the API needs to be slightly different as it always shows the existing plan without the ability to edit. If possible this should preselect a plan that is passed to the API.

**Comment by matthewelwell** [comment]
Ok, a bit of digging and looking through chargeee's unusually poor documentation, it turns out we just need to add the plan id of the plan the user wants to switch to when getting the hosted page. 

To achieve this, I've updated the endpoint slightly so that it better describes what's happening. 

The endpoint now looks like: 

```
POST /api/organisations/:id/get-hosted-page-url-for-subscription-upgrade

 + request 
{
    "plan_id": "startup"
}

 + response
{
    "url": "https://some.chargebee.url/page/id"
}
```

@kyle-ssg this is currently in a PR on the API [here](https://github.com/Flagsmith/flagsmith/pull/514) so once that's merged you can test it out on staging.

**Comment by dabeeeenster** [comment]
The plan IDs are:

- `startup-v2`
- `scale-up-v2`

**Comment by kyle-ssg** [comment]
Looks good against staging, though it doesn't work against production (maybe that's known but raising here just in case, get-hosted-page-url-for-subscription-upgrade returns subscription_id: ["This field may not be null."])

**Comment by kyle-ssg** [comment]
Frontend's live under https://github.com/Flagsmith/flagsmith/pull/544 under flag upgrade_subscription

**Comment by matthewelwell** [comment]
I'll look at handling that better but the above just means that the organisation you're trying to request the page for doesn't have a subscription, or their subscription doesn't have an id (maybe it's some manual subscription or something).
