### ISSUE TITLE
Initial value of the feature with a maximum length of 20000 characters

### ISSUE THREAD

**Issue by jhordan-gupy** [SolidStateGroup/bullet-train-api#3162]
**Is your feature request related to a problem? Please describe.**

I'm testing FlagSmith as an alternative for a remote configuration system and I thought about the possibility of using it to provide internationalization files for my frontend applications. however, it didn't work out very well because my translation file has more than 20000 characters. I would like to understand why the "initial_value" field is a models.CharField with max_length=20000 and the "description" field is a "models.TextField" since the "initial_value" value can be a JSON file.

Another note, there is no validation on the front end to show the maximum size of the value field

**Describe the solution you'd like**

Change the `initial_value` property from `models.CharField` to `models.TextField` in the `Feature` model in the `api/features/models.py` file.

**Describe alternatives you've considered**

Change the `initial_value` property from `models.CharField` to `models.TextField` in the `Feature` model in the `api/features/models.py` file.

**Additional context**
![image](https://github.com/Flagsmith/flagsmith/assets/123982011/9b2ef87f-bbae-42a2-be14-61263a06b075)

![image](https://github.com/Flagsmith/flagsmith/assets/123982011/227b98ea-64cf-40c3-8579-d63d721fba5b)

![image](https://github.com/Flagsmith/flagsmith/assets/123982011/56100c9d-d952-4529-b099-a9e9f938e08d)

**Comment by vicheanath** [comment]
Interesting can I try this issue? it good if you assigned to me

**Comment by matthewelwell** [comment]
@jhordan-gupy we do have to limit the size of this data in some way, it is not meant to be used to store large blobs of data. This data is stored in multiple places and also returned in a single API endpoint alongside other flags, if this becomes too large, we may breach certain storage limits in our infrastructure stack, and the payload size on the API could become unmanageable.

If you want to use flagsmith for internationalisation, I would recommend breaking it down into individual strings of data, rather than large JSON blobs.

**Comment by jhordan-gupy** [comment]
> @jhordan-gupy we do have to limit the size of this data in some way, it is not meant to be used to store large blobs of data. This data is stored in multiple places and also returned in a single API endpoint alongside other flags, if this becomes too large, we may breach certain storage limits in our infrastructure stack, and the payload size on the API could become unmanageable.
> 
> If you want to use flagsmith for internationalisation, I would recommend breaking it down into individual strings of data, rather than large JSON blobs.

It makes perfect sense, I just don't understand why the description field accepts my translation JSON file and the value field doesn't. Anyway, thanks for the explanation.

**Comment by matthewelwell** [comment]
> I just don't understand why the description field accepts my translation JSON file

Because the description is not part of the data which is stored in certain (more restricted) parts of our application, and is not returned via the API. A lot of these restrictions are enforced on us as part of our SaaS application but unpicking those / implementing dynamic data types here would be quite difficult. 

I am going to go ahead and close this issue for now but please let me know if you have further questions.
