### ISSUE TITLE
API Usage Alerting

### ISSUE THREAD

**Issue by gnumoreno** [SolidStateGroup/bullet-train-api#3236]
**Is your feature request related to a problem? Please describe.**

Sometimes customers are caught by surprise with API usage and overages.

**Describe the solution you'd like**

Customers would like to get alerts for basic usage: 

- Close to maxing out API usage.
- Anomalous Behaviour (ex.: large spike)

**Describe alternatives you've considered**

NA

**Additional context**

Loosely related to #2980

**Comment by zachaysan** [comment]
Thresholds for close to maxing out API Usage are
- 75%
- 90%
- 100%
- 120%

Must be configurable to the plan levels, since if we're introducing hard limits they should be different on different plans.

Must run on SaaS and possibly Private Cloud, but not necessary for on-prem. So control this via environment variable.
