### ISSUE TITLE
Filter flags in dashboard based on flag state

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3243]
It would be useful to be able to filter flags based on both their boolean and text values. Suggest adding another dropdown here titled "State" which opens a drop down to allow this:

<img width="1129" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/341c0fe1-b905-405c-a19e-1ac50a3ddace">

**Comment by GarvitSinghal47** [comment]
@dabeeeenster , I'm interested in contributing to this if you're open to it.

**Comment by dabeeeenster** [comment]
Yes that would be great thanks!

**Comment by matthewelwell** [comment]
Re-opening for 2 reasons: 

 1. The flag on the FE hasn't been enabled yet
 2. There seems to be scenarios where it doesn't work correctly, e.g. see the 'Demo' environment in the 'Flagsmith Website'. Screenshot below. 

<img width="1184" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/538769ea-4fdc-4d03-adc6-6634f7323920">

Given that these are 2 features that we use heavily in demos, I imagine it could be something versioning related since we often demo change requests using these features.

**Comment by matthewelwell** [comment]
@zachaysan looking into this, I believe it's because we're using `FeatureState.get_live_feature_states()` which actually (and perhaps confusingly) returns _all_ feature states which are considered 'live' to the engine, but doesn't (as we expected it to) only return the _latest_ live version. We should (I believe) change `features/views.py#L235-L238` to use `features.versioning.versioning_service.get_environment_flags_list` instead.
