### ISSUE TITLE
Boolean feature state changes in versioning v2 are not saved to audit logs

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#4051]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

See reproduction steps.

### Steps To Reproduce

1. Go to any environment with Versioning v2 enabled
2. Change the boolean state of any feature (not the remote config value) and save changes

This change is not reflected in the audit log.

### Expected behavior

All changes should be saved to the audit log.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/829698/1dd75192-1159-423e-9744-508fc5c33a67

**Comment by matthewelwell** [comment]
This behaviour is being resolved as follows: 

 1. I have added logic to create an audit log record when a new version is published for a given feature
 2. This audit log record will link directly to the history to show the change details in the new version
 
 The first PR for this is here: #4064, the next stage is to implement the FE. 
 
@kyle-ssg I'm using this issue here to provide the information about the changes we discussed earlier today. 

Some details you will need to know: 

 1. The AuditLog record will have `related_object_type=EF_VERSION` and `related_object_uuid=<uuid>` - this will be how you determine the uuid to link to the new version page we discussed. 
 2. The endpoint to retrieve a feature version has been added (you can see it [here](https://api-staging.flagsmith.com/api/v1/docs/#/api/api_v1_environments_features_versions_read)) and includes the `previous_version_uuid` attribute which you can use to get the previous version for comparison purposes.
