### ISSUE TITLE
All code examples should be instance-aware

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#4130]
Thanks to @rolodato for reporting this.

For every Flagsmith deployment besides the default Flagsmith SaaS environment, a correct base URL should be added to all SDK init code in all of the code examples.

**Comment by rolodato** [comment]
@kyle-ssg Apologies, I wasn't able to review this before it was merged. A custom Flagsmith-on-Flagsmith API URL is optional and is not provided by default in our [Docker Compose setup](https://github.com/Flagsmith/flagsmith/blob/6ba44f844bdb5c5295edb71da1d9396c8ec5755c/docker-compose.yml), which is a common entrypoint for self-hosting customers. Customers without a custom Flagsmith-on-Flagsmith URL will still see the default Edge API URLs.

Is it feasible to use the actual Flagsmith API URL instead of whatever is being used for Flagsmith-on-Flagsmith? I have a similar need when deriving SAML ACS URLs here: https://github.com/Flagsmith/flagsmith/pull/4494
