### ISSUE TITLE
Add a convenient permissions view for group/project/organisation admins

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#4269]
### Is your feature request related to a problem? Please describe.

To check a given users' permissions, one currently needs to navigate between projects and groups. This is becoming very cumbersome when a number of projects and groups increases.

### Describe the solution you'd like.

1. When clicking on a user, a view that shows all the groups that user is a member of.
2. A consolidated view to see all permissions granted to a specific user or group across projects and environments. This should list only the granted permissions, not the projects/environments where the user/group has no permissions.

### Describe alternatives you've considered

- Manual navigation through each group to find user memberships.
- Clicking on each project and environment to find granted permissions for users/groups.

**Comment by kyle-ssg** [comment]
> 1. When clicking on a user, a view that shows all the groups that user is a member of.

I've added this with the ability to adjust their groups, however I just need group_admin returning from the /groups endpoint for the users so we can see if they are a group admin. See https://github.com/Flagsmith/flagsmith/pull/4312

> 2. A consolidated view to see all permissions granted to a specific user or group across projects and environments. This should list only the granted permissions, not the projects/environments where the user/group has no permissions.

I believe this would require API, we can only get permissions for a specific environment or project at the moment. This could be done as a separate issue perhaps since 1 just needs an added field.

**Comment by kyle-ssg** [comment]
@khvn26 @matthewelwell is there any chance we can do this at some point, just need to add group_admin to the organisations/:id/groups/ endpoint
