### ISSUE TITLE
Prevent Flag Defaults settings makes identity flags unusable

### ISSUE THREAD

**Issue by azriel46d** [SolidStateGroup/bullet-train-api#4771]
### How are you running Flagsmith

- [x] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

in [CreateFlag.js](https://github.com/Flagsmith/flagsmith/blob/main/frontend/web/components/modals/CreateFlag.js#L1905-L1910) the `prevent_flag_defaults` is passed as a  parameter to the `<Value />` component, in which basically the input for `hideValue` is set to true. This makes an identity override unusable unless this project setting is disabled

### Steps To Reproduce

1. Go to project Settings
2. Enable `Prevent Flag Defaults` 
3. Go on an environment 
4. Select a flag
5. Attempt to override the value for a particular user

### Expected behavior

As a user I should still be able to override a flag for a particular identity.

**Comment by matthewelwell** [comment]
Thanks @azriel46d , I have been able to reproduce this, and I am adding the below screenshot to help illustrate the issue. 

![Image](https://github.com/user-attachments/assets/cf37a5e5-a783-4831-bfe6-cdfecc3494f5)

If you're willing to submit a PR, we'd gratefully receive it - otherwise, we'll look to fix it up as soon as we can.
