### ISSUE TITLE
Invitation Emails

### ISSUE THREAD

**Issue by malthauser** [SolidStateGroup/bullet-train-api#560]
We need to make our system emails better:

1. The email sender is "noreply@flagsmith.com". This should come from support@flagsmith.com or team@flagsmith.com

Example of email showing up in inbox (you can't tell it's from Flagsmith):
![Screen Shot 2021-12-08 at 11 20 53 AM](https://user-images.githubusercontent.com/661018/145193848-6b3c2fef-e6c3-43ef-bbe9-d32b152ef76d.png)

2. There is a "." at the end of the link that users are supposed to copy/paste into the browser. When you accidentally copy the "." you get a failed request on the link. We should delete that "." to avoid these situations.

![Screen Shot 2021-12-08 at 11 19 57 AM](https://user-images.githubusercontent.com/661018/145193506-f56d5d47-f5f8-42d4-b78d-56fa437e81ff.png)

**Comment by matthewelwell** [comment]
The address can be changed using the environment variable `SENDER_EMAIL`, although this will update it for all emails from the platform (which I've listed below). I'll update this to `support@` unless anyone says otherwise. 

For reference, the only emails that are sent from the platform are: 

 * Usage reports (for Self Hosted installs)
 * Organisation cancelled
 * Organisation over seats limit
 * Invite user
 * Password reset
