### ISSUE TITLE
Users with read only permissions to Segments should get read only view of Segment Overrides

### ISSUE THREAD

**Issue by chris-basis** [SolidStateGroup/bullet-train-api#700]
Hi! Fairly new Flagsmith user here, but I ran into an issue where there are segments set up for a feature flag of which I am a member of, but I can't see that the segment even exists on a flag without being under the admin role. I could be missing a setting here, so not necessarily a bug, but a teammate and I searched around for over an hour and we weren't able to figure out how to grant this to non-admins.

The questions:

1. Why am I not able to see what segments belong to a feature flag without admin privileges? 
2. What setting can I change to give our devs permissions to view what segments are overriding a flag without being a full administrator?

Screenshots for context --- First without admin privileges --- Second with admin privileges
![image](https://user-images.githubusercontent.com/95369968/150366075-b94b73b6-d6e8-4d03-b7f0-a0919b9cc369.png)

---
![image](https://user-images.githubusercontent.com/95369968/150365966-c62e3cc6-b3fe-425a-9c77-195bcda93e50.png)

**Comment by dabeeeenster** [comment]
Hi @chris-basis thanks for the report. Can you just confirm - is this on our SaaS service or are you self hosting?

**Comment by chris-basis** [comment]
> Hi @chris-basis thanks for the report. Can you just confirm - is this on our SaaS service or are you self hosting?

Self hosting on the latest version (2.14.4) on both FE/BE as far as I know.

**Comment by dabeeeenster** [comment]
Just reading over this - this behaviour is by design. 

Modifying Segment definitions can affect the flag values are returned across all Environments, and so it's not feasible to provide someone with less than Project Admin priveleges access to writing to this data. 

I'm thinking you would have expected in that case to see a read only version of the Segment overrides in this instance?

**Comment by chris-basis** [comment]
To your last point, that's exactly correct. I can dive into the 'Users' list and find my user and see that the segment is enabled, but it would be helpful to see what the segment's criteria is.

Additional context - We use this FF to distinguish between dev-only accounts, and I had no idea it had a segment attached to it at first glance, so it caused some confusion on the team because I assumed it was just disabled everywhere (which it is without the segment overrides)

**Comment by dabeeeenster** [comment]
Righto thanks - we will get on it!

**Comment by chris-basis** [comment]
> Righto thanks - we will get on it!

Awesome! Thanks for the fast replies!

**Comment by kyle-ssg** [comment]
Having looked into this it turned out that users now only need to have edit feature state permissions (or environment admin-level permissions until https://github.com/Flagsmith/flagsmith/issues/578 is live). 

Historically, segment overrides were set per project but this was changed to take effect per environment and thus users only need to be able to manage features for that environment. Thanks for bringing this to our attention @chris-basis!
