### ISSUE TITLE
Slack integration limited to 1000 channels

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#816]
If a Slack org as > 1000 channels, some don't show up. Need to increase/page/real time search.

**Comment by matthewelwell** [comment]
@gagantrivedi as discussed this morning, since Slack's API doesn't support search on name I think we have a few options: 

 1. Add an option for the user to choose switch between public and private channels and use the `type` filter on the slack API
 2. Grab the first 1000 private, then the first 1000 public automatically on the BE and then provide those 2000 channels to the FE for searching
 3. Add an option to manually enter the channel ID from the FE

The problem with 1 & 2 is that we'd still fall down if a user had more than 1000 public or private channels. Hence, my preference here is option 3 as it is completely foolproof in case we have users that have more than 1000 public or private channels. It's perhaps a bit more work (for us AND the user) but it's completely robust.

**Comment by dabeeeenster** [comment]
OK yep lets do that.

**Comment by gagantrivedi** [comment]
I think the back-end part needed for option 3 is already implemented.
![image](https://user-images.githubusercontent.com/18366226/156334412-b621cab9-8019-4ce2-97d0-f24480b7561c.png)

**Comment by matthewelwell** [comment]
As discussed, we need to do some validation on the BE when a user sends a channel ID to verify that they are authorised to send messages to that channel (otherwise we'll just throw an error when trying to send a message there once enabled).

That should effect the FE integration here though.

**Comment by kyle-ssg** [comment]
Slack integrations allow you to set a custom channel ID
