### ISSUE TITLE
Allow users to change their email address

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#887]
Users should be able to change their email address. Suggested flow:

- Log in
- Enter new email address and confirm with password
- Email sent to previous email address to notify that the email on their Flagsmith account has been updated and they should contact Flagsmith support if there are any issues

**Comment by matthewelwell** [comment]
@dabeeeenster I'm wondering here if we need to send the confirmation email? I feel like it would be sufficient to trigger an email to the previous email address to say that it's been updated. What do you think?

**Comment by dabeeeenster** [comment]
Yes agreed email to alert is fine.

**Comment by matthewelwell** [comment]
Great, I've updated the description of the ticket.

**Comment by novakzaballa** [comment]
@matthewelwell @dabeeeenster I have a PR for this ticket. After the change is made should we log out the user and ask to re-login using the new email address or just show update the Edit user page to show the new email address? Currently, I just updated the local email address value just like we do with the other editable attributes.
Also, I was not able to test whether the email notification has been sent since I don't have a user in our staging environment. 
This feature is behind the flag  `change_email` which is enabled for staging and disabled for production.

**Comment by dabeeeenster** [comment]
I think we should log the user out.
