### ISSUE TITLE
Audit log loading page message needs improving

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#909]
Currently when loading the audit log the message `You have no log messages for your project.` appears. This is wrong. It should state `Audit log messages are loading` ideally with a spinner.

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

**Comment by kyle-ssg** [comment]
I'll add this but you're mainly seeing now this due to the audit log paging being broken on the backend from what I can see. It's returning 3400 results with page_size=40.

Perhaps https://github.com/Flagsmith/flagsmith/issues/738 needs deploying? I'm pretty sure I saw this working at one point though.

**Comment by dabeeeenster** [comment]
@gagantrivedi can you have a look!

**Comment by kyle-ssg** [comment]
It'd be good to sort the environment query parameter as part of this.

![image](https://user-images.githubusercontent.com/8608314/162568595-2bf36036-2291-437d-b1b4-bb94a74b216f.png)


Trying this out with an environment id (not API key), it doesn't seem to have any effect.

If this works we can add an audit log nav item within each environment for environment admins.

**Comment by kyle-ssg** [comment]
Loading / debouncing added in https://github.com/Flagsmith/flagsmith/pull/940#partial-pull-merging but the above still needs doing
