### ISSUE TITLE
fix issue where errors return as csrf when they are not

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#926]

**Comment by matthewelwell** [comment]
This is because of the 'catch all' view that we have [here](https://github.com/Flagsmith/flagsmith/blob/main/api/app/urls.py#L67). The reason that we're seeing 'erroneous' CSRF errors is because the `views.index` method (a) doesn't expect to receive any requests other than GET but is not coded as such and (b) has not been marked as `@csrf_exempt`. 

There are a couple of options for solving this: 

 1. Mark this view as `csrf_exempt` by adding the decorator and manually return a 404 (or 415?) when we receive a request other than a GET (or OPTIONS?)
 2. Simply remove this catch all view - I'm not entirely sure why we have it? Perhaps it's necessary when running in the single container but if we remove it then the application will correctly just return a 404 and perhaps we should look into adding some kind of default 404 page? 

Perhaps @dabeeeenster might know why it's there?

**Comment by dabeeeenster** [comment]
No idea why it's there. Returning 404 for all non-existing pages seems like the correct response to me.
